#!/bin/sh /etc/rc.common
USE_PROCD=1
START=96
STOP=10

start_service() {
    config='/etc/router-wgpay-topology-delivery.conf'
    [ -r "$config" ] || return 1
    . "$config"
    [ "${TOPOLOGY_DELIVERY_ENABLED:-0}" = 1 ] || return 0
    procd_open_instance
    procd_set_param command /usr/local/sbin/router-wgpay-topology-delivery-loop.sh
    procd_set_param respawn 5 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
