#!/bin/sh /etc/rc.common

START=96
STOP=10
USE_PROCD=1

PROG="/usr/local/sbin/router-egress-emergency-decision-hook.sh"

start_service() {
  procd_open_instance
  procd_set_param command "$PROG" --loop --quiet
  procd_set_param respawn 3600 5 5
  procd_close_instance
}
