#!/bin/sh /etc/rc.common
START=96
STOP=8
USE_PROCD=1

start_service() {
    config='/etc/router-egress-provider-direct.conf'
    [ -r "$config" ] || return 1
    . "$config"
    [ "${PROVIDER_DIRECT_ENABLED:-0}" = 1 ] || return 0
    procd_open_instance
    procd_set_param command /usr/local/sbin/router-egress-provider-direct.sh --loop
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
